#!/usr/bin/env python3
"""Build the C48_ATM ecFlow def file.

A minimal forecast-only ATM-only single-cycle suite that mirrors the
C48_ATM Rocoto experiment (dev/ci/cases/pr/C48_ATM.yaml):

  * mode:        forecast-only
  * app:         ATM
  * resolution:  C48
  * cycles:      one (idate == edate == 2021032312)
  * task chain:  stage_ic -> fcst -> atmos_product -> arch_vrfy -> cleanup

Generated def goes to $EXPDIR/gfs_c48_atm.def (default
$DEV_ROOT/c48_atm/expdir/), not the repo.

Usage::

    # Default location:
    python3 dev/ecf/c48_atm/build_def.py

    # Custom output:
    python3 dev/ecf/c48_atm/build_def.py --out /path/to/gfs_c48_atm.def
"""

import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]

USER = os.environ.get("USER", "anton.fernando")
HOMEgfs_ABS = str(REPO_ROOT)
DEV_ROOT = "/lfs/h2/emc/global/noscrub/{}/c48_atm".format(USER)
EXPDIR_DEFAULT = "{}/expdir".format(DEV_ROOT)
ECF_FILES = "{}/dev/ecf/c48_atm/scripts".format(HOMEgfs_ABS)
ECF_INCLUDE = "{}/dev/ecf/c48_atm/include".format(HOMEgfs_ABS)
ECF_LOGHOST = "dlogin01"
ECF_PORT = "2137"

# Single hard-coded cycle that matches the Rocoto YAML's idate=2021032312.
PDY = "20210323"
CYC = "12"


def build_def():
    return "\n".join([
        "# Auto-generated by dev/ecf/c48_atm/build_def.py",
        "# C48 forecast-only single-cycle ATM test.",
        "# Mirrors dev/ci/cases/pr/C48_ATM.yaml.",
        "#",
        "# Prerequisite directories (created on disk):",
        "#   mkdir -p {}/{{tmp,com,logs}}".format(DEV_ROOT),
        "#",
        "suite gfs_c48_atm",
        "  family primary",
        "    # ---- repo / build paths ----",
        "    edit HOMEgfs '{}'".format(HOMEgfs_ABS),
        "    edit HOMEglobal '{}'".format(HOMEgfs_ABS),
        "    edit PACKAGEHOME '%HOMEgfs%'",
        "    edit gfs_ver 'v17.0'",
        "    # ---- ecflow client / job submission (absolute paths) ----",
        "    edit ECF_LOGHOST '{}'".format(ECF_LOGHOST),
        "    edit ECF_PORT '{}'".format(ECF_PORT),
        "    edit ECF_FILES '{}'".format(ECF_FILES),
        "    edit ECF_INCLUDE '{}'".format(ECF_INCLUDE),
        "    edit ECF_JOB_CMD 'qsub %ECF_JOB% 1> %ECF_JOBOUT% 2>&1'",
        "    edit ECF_KILL_CMD 'qdel %ECF_RID%'",
        "    edit ECF_STATUS_CMD 'qstat %ECF_RID% > %ECF_JOB%.stat 2>&1'",
        "    edit ecflow_ver '5.6.0'",
        "    # ---- env / project metadata ----",
        "    edit NET 'gfs'",
        "    edit RUN 'gfs'",
        "    edit PROJ 'GFS'",
        "    edit PROJENVIR 'DEV'",
        "    edit MACHINE_SITE 'development'",
        "    edit ENVIR 'prod'",
        "    edit QUEUE 'dev'",
        "    edit QUEUE_ARCH 'dev_transfer'",
        "    edit PDY '{}'".format(PDY),
        "    # ---- dev workspace ----",
        "    edit DATAROOT '{}/tmp'".format(DEV_ROOT),
        "    edit COMROOT '{}/com'".format(DEV_ROOT),
        "    edit LOGROOT '{}/logs'".format(DEV_ROOT),
        "    edit OUTPUTDIR '{}/output'".format(DEV_ROOT),
        "    edit KEEPDATA 'YES'",
        "    # ---- production-flag stubs (test mode) ----",
        "    edit PARATEST 'NO'",
        "    edit DBNLOG 'NO'",
        "    edit SENDDBN 'NO'",
        "    edit SENDDBN_NTC 'NO'",
        "    edit SENDCANNEDDBN 'NO'",
        "    edit COMPATH ' '",
        "    edit MAILTO ' '",
        "    edit rrfs_ver ' '",
        "    family {}".format(CYC),
        "      edit CYC '{}'".format(CYC),
        "      family gfs",
        "        edit RUN 'gfs'",
        "        family init",
        "          task jgfs_stage_ic",
        "        endfamily",
        "        family forecast",
        "          task jgfs_fcst",
        "            trigger ../init/jgfs_stage_ic == complete",
        "        endfamily",
        "        family product",
        "          family atmos",
        "            task jgfs_atmos_product",
        "              trigger ../../forecast/jgfs_fcst == complete",
        "          endfamily",
        "        endfamily",
        "        family arch",
        "          task jgfs_arch_vrfy",
        "            trigger ../product/atmos/jgfs_atmos_product == complete",
        "          task jgfs_cleanup",
        "            trigger jgfs_arch_vrfy == complete",
        "        endfamily",
        "      endfamily",
        "    endfamily",
        "  endfamily",
        "endsuite",
        "",
    ])


def main():
    import argparse
    parser = argparse.ArgumentParser(
        description="Build the C48_ATM ecFlow def file.",
    )
    parser.add_argument(
        "--out",
        help="Output path (default: $EXPDIR/gfs_c48_atm.def, or "
             "{}/gfs_c48_atm.def if EXPDIR is unset)".format(EXPDIR_DEFAULT),
    )
    args = parser.parse_args()

    if args.out:
        out_path = Path(args.out)
    else:
        expdir = os.environ.get("EXPDIR", EXPDIR_DEFAULT)
        out_path = Path(expdir) / "gfs_c48_atm.def"

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(build_def())
    n = sum(1 for _ in out_path.read_text().splitlines())
    print("Wrote {} ({} lines)".format(out_path, n))
    print()
    print("Next steps:")
    print("  mkdir -p {}/{{tmp,com,logs}}".format(DEV_ROOT))
    print("  ecflow_client --delete=force=yes /gfs_c48_atm 2>/dev/null")
    print("  ecflow_client --load={}".format(out_path))
    print("  ecflow_client --suspend=/gfs_c48_atm")
    print("  ecflow_client --resume=/gfs_c48_atm")
    print("  ecflow_client --begin=gfs_c48_atm")


if __name__ == "__main__":
    main()
